/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchwimmteichRouteImport } from './routes/schwimmteich'
import { Route as PoolabdeckungenRouteImport } from './routes/poolabdeckungen'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as FolienFarbenDesignRouteImport } from './routes/folien-farben-design'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as DaecherRouteImport } from './routes/daecher'
import { Route as AufbauUnsererPoolsRouteImport } from './routes/aufbau-unserer-pools'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoolabdeckungenIndexRouteImport } from './routes/poolabdeckungen.index'

const SchwimmteichRoute = SchwimmteichRouteImport.update({
  id: '/schwimmteich',
  path: '/schwimmteich',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolabdeckungenRoute = PoolabdeckungenRouteImport.update({
  id: '/poolabdeckungen',
  path: '/poolabdeckungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const FolienFarbenDesignRoute = FolienFarbenDesignRouteImport.update({
  id: '/folien-farben-design',
  path: '/folien-farben-design',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const DaecherRoute = DaecherRouteImport.update({
  id: '/daecher',
  path: '/daecher',
  getParentRoute: () => rootRouteImport,
} as any)
const AufbauUnsererPoolsRoute = AufbauUnsererPoolsRouteImport.update({
  id: '/aufbau-unserer-pools',
  path: '/aufbau-unserer-pools',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolabdeckungenIndexRoute = PoolabdeckungenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PoolabdeckungenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aufbau-unserer-pools': typeof AufbauUnsererPoolsRoute
  '/daecher': typeof DaecherRoute
  '/datenschutz': typeof DatenschutzRoute
  '/folien-farben-design': typeof FolienFarbenDesignRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/poolabdeckungen': typeof PoolabdeckungenRouteWithChildren
  '/schwimmteich': typeof SchwimmteichRoute
  '/poolabdeckungen/': typeof PoolabdeckungenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aufbau-unserer-pools': typeof AufbauUnsererPoolsRoute
  '/daecher': typeof DaecherRoute
  '/datenschutz': typeof DatenschutzRoute
  '/folien-farben-design': typeof FolienFarbenDesignRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/schwimmteich': typeof SchwimmteichRoute
  '/poolabdeckungen': typeof PoolabdeckungenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aufbau-unserer-pools': typeof AufbauUnsererPoolsRoute
  '/daecher': typeof DaecherRoute
  '/datenschutz': typeof DatenschutzRoute
  '/folien-farben-design': typeof FolienFarbenDesignRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/poolabdeckungen': typeof PoolabdeckungenRouteWithChildren
  '/schwimmteich': typeof SchwimmteichRoute
  '/poolabdeckungen/': typeof PoolabdeckungenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aufbau-unserer-pools'
    | '/daecher'
    | '/datenschutz'
    | '/folien-farben-design'
    | '/impressum'
    | '/kontakt'
    | '/poolabdeckungen'
    | '/schwimmteich'
    | '/poolabdeckungen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aufbau-unserer-pools'
    | '/daecher'
    | '/datenschutz'
    | '/folien-farben-design'
    | '/impressum'
    | '/kontakt'
    | '/schwimmteich'
    | '/poolabdeckungen'
  id:
    | '__root__'
    | '/'
    | '/aufbau-unserer-pools'
    | '/daecher'
    | '/datenschutz'
    | '/folien-farben-design'
    | '/impressum'
    | '/kontakt'
    | '/poolabdeckungen'
    | '/schwimmteich'
    | '/poolabdeckungen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AufbauUnsererPoolsRoute: typeof AufbauUnsererPoolsRoute
  DaecherRoute: typeof DaecherRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FolienFarbenDesignRoute: typeof FolienFarbenDesignRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  PoolabdeckungenRoute: typeof PoolabdeckungenRouteWithChildren
  SchwimmteichRoute: typeof SchwimmteichRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schwimmteich': {
      id: '/schwimmteich'
      path: '/schwimmteich'
      fullPath: '/schwimmteich'
      preLoaderRoute: typeof SchwimmteichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poolabdeckungen': {
      id: '/poolabdeckungen'
      path: '/poolabdeckungen'
      fullPath: '/poolabdeckungen'
      preLoaderRoute: typeof PoolabdeckungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folien-farben-design': {
      id: '/folien-farben-design'
      path: '/folien-farben-design'
      fullPath: '/folien-farben-design'
      preLoaderRoute: typeof FolienFarbenDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daecher': {
      id: '/daecher'
      path: '/daecher'
      fullPath: '/daecher'
      preLoaderRoute: typeof DaecherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aufbau-unserer-pools': {
      id: '/aufbau-unserer-pools'
      path: '/aufbau-unserer-pools'
      fullPath: '/aufbau-unserer-pools'
      preLoaderRoute: typeof AufbauUnsererPoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poolabdeckungen/': {
      id: '/poolabdeckungen/'
      path: '/'
      fullPath: '/poolabdeckungen/'
      preLoaderRoute: typeof PoolabdeckungenIndexRouteImport
      parentRoute: typeof PoolabdeckungenRoute
    }
  }
}

interface PoolabdeckungenRouteChildren {
  PoolabdeckungenIndexRoute: typeof PoolabdeckungenIndexRoute
}

const PoolabdeckungenRouteChildren: PoolabdeckungenRouteChildren = {
  PoolabdeckungenIndexRoute: PoolabdeckungenIndexRoute,
}

const PoolabdeckungenRouteWithChildren = PoolabdeckungenRoute._addFileChildren(
  PoolabdeckungenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AufbauUnsererPoolsRoute: AufbauUnsererPoolsRoute,
  DaecherRoute: DaecherRoute,
  DatenschutzRoute: DatenschutzRoute,
  FolienFarbenDesignRoute: FolienFarbenDesignRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  PoolabdeckungenRoute: PoolabdeckungenRouteWithChildren,
  SchwimmteichRoute: SchwimmteichRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
